### PR TITLE
Added Polish lang

### PR DESCRIPTION
**Pull request by peeery**

### CODE REVIEW

**Comment by sboily** [comment]
Hello Peery,

Please be careful you open many PR instead of update your PR.

**Comment by peeery** [comment]
Hello @sboily 
I don't know how to update my PR. If You can help me, Please add Polish translation to XiVO-client.

Thank you in advance

**Comment by sduthil** [comment]
Hi @peeery, I merged all your PR in #21 . I'll close the others soon. Thanks for contributing!

**Comment by peeery** [comment]
Thanks for Help

**Pull request closed without merging**
